services:
  # Serviço PostgreSQL
  - type: pserv
    name: hublocal-postgres
    env: docker
    plan: standard
    dockerfilePath: ./Dockerfile.postgres
    disk:
      name: postgres-data
      mountPath: /var/lib/postgresql/data
      sizeGB: 10
    envVars:
      - key: POSTGRES_PASSWORD
        sync: false
      - key: POSTGRES_USER
        value: postgres
      - key: POSTGRES_DB
        value: postgres

  # Serviço Backend
  - type: web
    name: hublocal-backend
    env: docker
    dockerfilePath: ./backend/Dockerfile
    plan: standard
    healthCheckPath: /
    envVars:
      - key: DATABASE_URL
        fromService:
          type: pserv
          name: hublocal-postgres
          envVarKey: POSTGRES_URL
      - key: JWT_SECRET
        sync: false
      - key: PORT
        value: 3001

  # Serviço Frontend
  - type: web
    name: hublocal-frontend
    env: docker
    dockerfilePath: ./frontend/Dockerfile
    plan: standard
    envVars:
      - key: REACT_APP_API_URL
        value: /api

  # Serviço Nginx
  - type: web
    name: hublocal-nginx
    env: docker
    dockerfilePath: ./Dockerfile.nginx
    plan: standard
    domains:
      - hublocal.onrender.com