services:
  # Serviço Web único (combinando frontend e backend)
  - type: web
    name: hublocal-app
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: JWT_SECRET
        sync: false
      - key: PORT
        value: 10000

  # Serviço Backend
  - type: web
    name: hublocal-backend
    env: docker
    dockerfilePath: ./backend/Dockerfile
    plan: standard
    healthCheckPath: /
    envVars:
      - key: DATABASE_URL
        fromService:
          type: pserv
          name: hublocal-postgres
          envVarKey: POSTGRES_URL
      - key: JWT_SECRET
        sync: false
      - key: PORT
        value: 3001

  # Serviço Frontend
  - type: web
    name: hublocal-frontend
    env: docker
    dockerfilePath: ./frontend/Dockerfile
    plan: standard
    envVars:
      - key: REACT_APP_API_URL
        value: /api

  # Serviço Nginx
  - type: web
    name: hublocal-nginx
    env: docker
    dockerfilePath: ./Dockerfile.nginx
    plan: standard
    domains:
      - hublocal.onrender.com